# Generated by Django 3.2.19 on 2023-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hall', models.CharField(max_length=200, verbose_name='Аудитория')),
                ('working_hours', models.CharField(max_length=200, verbose_name='Часы работы')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты для студентов',
                'verbose_name_plural': 'Контакты для студентов',
                'db_table': 'students_contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeachersContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_hall', models.CharField(max_length=200, verbose_name='Аудитория')),
                ('working_hours', models.CharField(max_length=200, verbose_name='Часы работы')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контакты для сотрудников',
                'verbose_name_plural': 'Контакты для сотрудников',
                'db_table': 'teachers_contacts',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='benefits',
            name='body',
            field=models.TextField(verbose_name='Текст льготы'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание льготы'),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Тема льготы'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='admin_upload',
            field=models.FileField(upload_to='media', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.TextField(verbose_name='Описание документа'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Тема документа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Тема новости'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='description',
            field=models.TextField(verbose_name='Описание пина'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='image_link',
            field=models.TextField(verbose_name='Ссылка на изображение пина'),
        ),
        migrations.AlterField(
            model_name='pins',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Тема пина'),
        ),
    ]
